// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['GOOGLE_API_KEY_WEB']!,
    appId: '1:535343213814:web:a9b89be55b9f67994f90d7',
    messagingSenderId: '535343213814',
    projectId: 'coocue-39d77',
    authDomain: 'coocue-39d77.firebaseapp.com',
    storageBucket: 'coocue-39d77.firebasestorage.app',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['GOOGLE_API_KEY_ANDROID']!,
    appId: '1:535343213814:android:8b7d119cea3595994f90d7',
    messagingSenderId: '535343213814',
    projectId: 'coocue-39d77',
    storageBucket: 'coocue-39d77.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['GOOGLE_API_KEY_IOS']!,
    appId: '1:535343213814:ios:a4f8692ab186dd614f90d7',
    messagingSenderId: '535343213814',
    projectId: 'coocue-39d77',
    storageBucket: 'coocue-39d77.firebasestorage.app',
    iosBundleId: 'com.example.coocue',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['GOOGLE_API_KEY_MACOS']!,
    appId: '1:535343213814:ios:a4f8692ab186dd614f90d7',
    messagingSenderId: '535343213814',
    projectId: 'coocue-39d77',
    storageBucket: 'coocue-39d77.firebasestorage.app',
    iosBundleId: 'com.example.coocue',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['GOOGLE_API_KEY_WINDOWS']!,
    appId: '1:535343213814:web:1931802ad25aa70e4f90d7',
    messagingSenderId: '535343213814',
    projectId: 'coocue-39d77',
    authDomain: 'coocue-39d77.firebaseapp.com',
    storageBucket: 'coocue-39d77.firebasestorage.app',
  );
}
